"""Auto-generated Pydantic models from the hpc-access OpenAPI schema.

Regenerate with:  python scripts/generate_models.py
"""

from __future__ import annotations

import datetime
import enum
from typing import Any
from uuid import UUID

from pydantic import BaseModel


@enum.unique
class Status(enum.Enum):
    """Status of a hpc user, group, or project."""

    INITIAL = "INITIAL"
    ACTIVE = "ACTIVE"
    DELETED = "DELETED"
    EXPIRED = "EXPIRED"


class ResourceData(BaseModel):
    """A resource request/usage for a group or project."""

    #: Storage on tier 1 in TiB (work).
    tier1_work: float = 0.0
    #: Storage on tier 1 in TiB (scratch).
    tier1_scratch: float = 0.0
    #: Storage on tier 2 (mirrored) in TiB.
    tier2_mirrored: float = 0.0
    #: Storage on tier 2 (unmirrored) in TiB.
    tier2_unmirrored: float = 0.0


class ResourceDataUser(BaseModel):
    """A resource request/usage for a user."""

    #: Storage on tier 1 in GiB (home).
    tier1_home: float = 0.0


class GroupFolders(BaseModel):
    """Folders for a group or project."""

    #: The work directory.
    tier1_work: str
    #: The scratch directory.
    tier1_scratch: str
    #: The mirrored directory.
    tier2_mirrored: str
    #: The unmirrored directory.
    tier2_unmirrored: str


class HpcUser(BaseModel):
    """Serializer for HpcUser model."""

    uuid: str = ...
    date_created: datetime.datetime = ...
    email: str = ...
    full_name: str = ...
    first_name: str = ...
    last_name: str = ...
    display_name: str = ...
    phone_number: str = ...
    primary_group: UUID = ...  # Record UUID
    resources_requested: Any = ...
    resources_used: Any = ...
    status: str = ...
    description: str = ...
    uid: int = ...
    username: str = ...
    expiration: datetime.datetime = ...
    home_directory: str = ...
    login_shell: str = ...
    removed: bool = ...
    current_version: int = ...


class HpcGroup(BaseModel):
    """Serializer for HpcGroup model."""

    uuid: str = ...
    date_created: datetime.datetime = ...
    owner: UUID = ...  # Record UUID
    delegate: UUID = ...  # Record UUID
    resources_requested: Any = ...
    resources_used: Any = ...
    status: str = ...
    description: str = ...
    gid: int = ...
    name: str = ...
    folders: Any = ...
    expiration: datetime.datetime = ...
    current_version: int = ...


class HpcProject(BaseModel):
    """Serializer for HpcProject model."""

    uuid: str = ...
    date_created: datetime.datetime = ...
    group: UUID = ...  # Record UUID
    delegate: UUID = ...  # Record UUID
    resources_requested: Any = ...
    resources_used: Any = ...
    status: str = ...
    description: str = ...
    gid: int = ...
    name: str = ...
    folders: Any = ...
    expiration: datetime.datetime = ...
    members: list[UUID] = ...
    current_version: int = ...
