on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      pr: ${{ steps.release.outputs.pr }}
      pr_head_ref: ${{ steps.release.outputs.pr_head_ref }}
    steps:
      # Release pull requests opened with GITHUB_TOKEN do not run the required checks
      - name: Create an app token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.HPC_ACCESS_CLI_APP_CLIENT_ID }}
          private-key: ${{ secrets.HPC_ACCESS_CLI_APP_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}
